# Generated by Django 3.0.3 on 2020-02-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(blank=True, max_length=64)),
                ('user_birthday', models.CharField(blank=True, max_length=64)),
                ('user_height', models.FloatField(blank=True)),
                ('user_weight', models.FloatField(blank=True)),
                ('user_gender', models.BooleanField(blank=True)),
                ('user_address', models.CharField(blank=True, max_length=64)),
                ('user_email', models.CharField(blank=True, max_length=64)),
                ('user_phone', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
