# Generated by Django 3.0.3 on 2020-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.FloatField(blank=True)),
                ('diastolic', models.FloatField(blank=True)),
                ('pulse', models.IntegerField(blank=True)),
                ('recorded_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
